# Generated by Django 4.2.1 on 2023-08-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="projects/")),
            ],
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="title",
        ),
        migrations.AddField(
            model_name="project",
            name="moreabout",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="pages",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="project_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="techstack",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_repo",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portfolio.project"
            ),
        ),
    ]
