# Generated by Django 4.2.1 on 2023-08-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_projectimage_delete_experience_delete_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_date",
            field=models.DateField(default=None),
        ),
    ]
