# Generated by Django 4.2.4 on 2023-08-25 18:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_project_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("url", models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("issuing_organization", models.CharField(default="", max_length=200)),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "certificate",
                    models.FileField(default=None, upload_to="certificates/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(default="", max_length=200)),
                ("degree", models.CharField(default="", max_length=100)),
                ("major", models.CharField(default="", max_length=100)),
                ("graduation_date", models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("date", models.DateField(default=None)),
                ("description", models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("proficiency", models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(default="", max_length=20)),
                ("url", models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(default="", max_length=100)),
                ("company", models.CharField(default="", max_length=200)),
                ("start_date", models.DateField(default=None)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(default="", max_length=200)),
                ("job_description", models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor.fields.RichTextField(default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="moreabout",
            field=ckeditor.fields.RichTextField(default=""),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=50)),
                ("last_name", models.CharField(default="", max_length=50)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(default="", max_length=254)),
                (
                    "phone",
                    models.CharField(default="(+91) 906-XXXX-100", max_length=20),
                ),
                ("curr_location", models.CharField(default="", max_length=200)),
                ("location", models.CharField(default="", max_length=200)),
                ("about", models.TextField()),
                ("blogs", models.ManyToManyField(blank=True, to="portfolio.blog")),
                (
                    "certifications",
                    models.ManyToManyField(blank=True, to="portfolio.certification"),
                ),
                (
                    "education",
                    models.ManyToManyField(blank=True, to="portfolio.education"),
                ),
                (
                    "interests",
                    models.ManyToManyField(blank=True, to="portfolio.interest"),
                ),
                (
                    "languages",
                    models.ManyToManyField(blank=True, to="portfolio.language"),
                ),
                (
                    "presentations",
                    models.ManyToManyField(blank=True, to="portfolio.presentation"),
                ),
                (
                    "projects",
                    models.ManyToManyField(blank=True, to="portfolio.project"),
                ),
                ("skills", models.ManyToManyField(blank=True, to="portfolio.skill")),
                (
                    "social_media",
                    models.ManyToManyField(blank=True, to="portfolio.socialmedia"),
                ),
                (
                    "work_experience",
                    models.ManyToManyField(blank=True, to="portfolio.workexperience"),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
