# Generated by Django 4.2.4 on 2023-08-26 00:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_blog_certification_education_interest_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="pages",
            field=ckeditor.fields.RichTextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=ckeditor.fields.RichTextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="techstack",
            field=ckeditor.fields.RichTextField(default="", max_length=500),
        ),
    ]
