# Generated by Django 4.2.4 on 2023-09-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_project_pages_alter_project_project_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(default=None, upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="certification",
            name="image",
            field=models.ImageField(default=None, upload_to="certificate/"),
        ),
        migrations.AddField(
            model_name="education",
            name="image",
            field=models.ImageField(default=None, upload_to="education/"),
        ),
        migrations.AddField(
            model_name="language",
            name="image",
            field=models.ImageField(default=None, upload_to="languages/"),
        ),
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(default=None, upload_to="skill/"),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="image",
            field=models.ImageField(default=None, upload_to="social/"),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="image",
            field=models.ImageField(default=None, upload_to="work/"),
        ),
    ]
