# Generated by Django 4.2.4 on 2023-09-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_blog_image_certification_image_education_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="aggregate",
            field=models.CharField(default="", max_length=20),
        ),
    ]
