# Generated by Django 4.2.4 on 2023-09-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_education_aggregate"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="image",
            field=models.ImageField(default=None, upload_to="interest/"),
        ),
    ]
