# Generated by Django 4.2.4 on 2023-09-02 16:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamiliarTech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("image", models.ImageField(default=None, upload_to="familiar/")),
            ],
        ),
        migrations.CreateModel(
            name="LibFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("image", models.ImageField(default=None, upload_to="frameworks/")),
            ],
        ),
        migrations.CreateModel(
            name="ToolPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("image", models.ImageField(default=None, upload_to="tools/")),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
