# Generated by Django 4.2.4 on 2023-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_subscribeemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribeemail",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
